[user]
name = "John Kurkowski"

[ui]
bookmark-list-sort-keys = ["committer-date-", "name"]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ":git"

[[--scope]]
--when.commands = ["diff", "log", "show"]
[--scope.ui]
pager = "delta --side-by-side"

[aliases]
lp = ["log", "--patch", "--no-graph", "--ignore-all-space"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
